routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/','HomeController@index');
Route::get('/category/{cslug}', 'HomeController@category_wise');
Route::get('/bangladesh', 'HomeController@bangladesh')->name('bangladesh');
Route::get('/international', 'HomeController@international')->name('international');
Route::get('/entertainment', 'HomeController@entertainment')->name('entertainment');
Route::get('/country', 'HomeController@country')->name('country');
Route::get('/politics', 'HomeController@politics')->name('politics');
Route::get('/economy', 'HomeController@economy')->name('economy');
Route::get('/sports', 'HomeController@sports')->name('Sports');
Route::get('/feature', 'HomeController@feature')->name('Feature');
Route::get('/cricket', 'HomeController@cricket')->name('Cricket');
Route::get('/football', 'HomeController@cricket')->name('Footbal');
Route::get('/hollywood', 'HomeController@hollywood')->name('hollywood');
Route::get('/bollywood', 'HomeController@bollywood')->name('bollywood');
Route::get('/lifestyle', 'HomeController@lifestyle')->name('lifestyle');
Route::get('/travel', 'HomeController@travel')->name('travel');
Route::get('/districts-news', 'HomeController@districts_news')->name('districts-news');
Route::get('/jokes', 'HomeController@jokes')->name('jokes');
Route::get('/opinion', 'HomeController@opinion')->name('opinion');
Route::get('/photo-gallery', 'HomeController@gallery')->name('gallery');
Route::get('/education', 'HomeController@education')->name('education');
Route::get('/health', 'HomeController@health')->name('health');
Route::get('/law-courts', 'HomeController@law_courts')->name('law-courts');
Route::get('/religion', 'HomeController@religion')->name('religion');
Route::get('/probash', 'HomeController@probash')->name('probash');
Route::get('/various', 'HomeController@various')->name('various');
Route::get('/technology', 'HomeController@technology')->name('technology');
Route::get('/literature', 'HomeController@literature')->name('literature');
Route::get('/jobs', 'HomeController@jobs')->name('jobs');
Route::get('/ekushey-book-fair', 'HomeController@ekushey_book_fair')->name('ekushey-book-fair');
Route::get('/archive', 'HomeController@archive')->name('archive');
//TAGS
Route::get('/topic/{ldTtitle}', 'HomeController@topic');
//ARTICLES
Route::get('/{category}/articles/{id}/{slug}', 'HomeController@article');
//DASHBOARD AREA
Auth::routes();
Route::get('/admin', 'AdminController@index')->name('Admin');
Route::get('/home_info', 'AdminController@home_info')->name('home_info');
//Category Route
Route::get('/category', 'CategoryController@index')->name('home');
Route::post('/categoryInsert', 'CategoryController@store')->name('Category Insert');
Route::delete('/category/delete', 'CategoryController@destroy');
Route::get('/category-edit/{categoryId}', 'CategoryController@category_edit')->name('');
Route::post('category_update', 'CategoryController@update')->name('');
Route::get('/category-delete/{categoryId}', 'CategoryController@category_delete')->name('');
Route::post('categoryStatus', array('as' => 'categoryStatus', 'uses' => 'CategoryController@categoryStatus'));
//SUBCATEGORY
Route::post('/subCategoryInsert','CategoryController@subCatStore')->name('Category Insert');
Route::post('get_subcategory','CategoryController@get_subcategory');
Route::get('/subcategory/{id}', 'CategoryController@ajaxsubCategory');
Route::resource('subcategory', 'SubcategoryController', ['except' => ['create']]);
Route::delete('/sub_category/delete', 'CategoryController@sub_destroy');
Route::post('subcatStatus', array('as' => 'subcatStatus', 'uses' => 'SubcategoryController@subcatStatus'));
//NEWS
Route::get('/allnews','NewsController@index')->name('news');
Route::get('/addNews', 'NewsController@addNews')->name('user');
Route::post('postInsert','NewsController@postInsert');
Route::get('/draft_post', 'NewsController@draft_post')->name('');
Route::get('/news-delete/{newsId}', 'NewsController@newsDelete')->name('news delete');
Route::get('/news-view/{newsId}', 'NewsController@newsView')->name('ad view');
Route::get('/news-edit/{newsId}', 'NewsController@newsEdit')->name('ad edit');
Route::get('newsfilter', 'NewsController@newsfilter')->name('newsfilter');
Route::post('newsfilterView', 'NewsController@newsfilterView')->name('newsfilter');
Route::post('postUpdate', 'NewsController@postUpdate')->name('News Update');
Route::get('/mypost','NewsController@myPost')->name('news');
Route::get('/days_news','NewsController@days_news')->name('news');

//ANALYTICS
Route::get('/google-analytics','AnalyticController@index')->name('google-analytics');
//advertisement
Route::get('/advertisement','AddsController@index')->name('advertisement');
Route::get('/videos', 'GalleryController@videos')->name('Videos');
//USER
Route::post('register_user','UserController@register')->name('update');
Route::get('/user', 'UserController@index')->name('user');
Route::get('/userAdd', 'UserController@userAdd')->name('Profile');
Route::post('profile-update','UserController@update')->name('update');
Route::post('update_user','UserController@update_user')->name('update');
Route::post('userStatus', array('as' => 'userStatus', 'uses' => 'UserController@userStatus'));
Route::get('/user-edit/{userId}', 'UserController@edit')->name('');
Route::get('/user_delete/{userId}', 'UserController@deleteUser')->name('deleteUser');
Route::get('/singleUser/{userId}', 'UserController@singleUser')->name('singleUser');
Route::get('/profile','UserController@profile')->name('User Profile');
Route::get('/profile-edit','UserController@profile_edit')->name('Profile');
Route::get('/profile-activity','UserController@profile_activity')->name('Profile');
Route::get('/subscriber', 'AdminController@subscriber')->name('subscriber');
//AREA
Route::post('get_district','DistrictController@get_district')->name('');
Route::post('get_upazila','UpazilaController@get_upazila')->name('');
Route::resource('division', 'DivisionController', ['except' => ['create']]);
Route::resource('district', 'DistrictController', ['except' => ['create']]);
Route::resource('upazila', 'UpazilaController', ['except' => ['create']]);
Route::resource('tags', 'TagsController', ['except' => ['create']]);
Route::post('tagStatus', array('as' => 'tagStatus', 'uses' => 'TagsController@tagStatus'));
//META
Route::post('updateMeta', 'AdminController@updateMeta')->name('Company Update');
//GALLERY
Route::get('gallery', 'GalleryController@index');
Route::get('gallery_add', 'GalleryController@gallery_add');
Route::post('galleryStore','GalleryController@galleryStore');
Route::post('galleryEdit/{galId}/','GalleryController@galleryEdit');
Route::get('galleryDelete/{galId}', 'GalleryController@galleryDelete')->name('');
//COMPANY info
Route::get('/company_info', 'CompanyController@index')->name('Company Info');
Route::post('companyInfo_save', 'CompanyController@companyInfo_save')->name('Company Update');
//COMMENT
Route::get('/comments', 'AdminController@comment')->name('comment');
Route::post('changeStatus', array('as' => 'changeStatus', 'uses' => 'NewsController@changeStatus'));
Route::post('featureStatus', array('as' => 'featureStatus', 'uses' => 'NewsController@featureStatus'));
Route::post('leadnewsStatus', array('as' => 'leadnewsStatus', 'uses' => 'NewsController@leadnewsStatus'));

app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
    //
}

resources/views/admin/area/district.blade.php
@extends('admin.layouts.app')
@section('title', 'Area | District')
@section('content')
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
              <!-- page start-->
              <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
              <section class="panel">
              <header class="panel-heading">District<span class="tools pull-right">
               <a class="btn" data-toggle="modal" href="#" data-toggle="modal" data-target="#create-item">Add</a>
                <a href="javascript:;" class="fa fa-chevron-down"></a>
                <a href="javascript:;" class="fa fa-times"></a>
             </span>
             @include('admin.layouts.message')
              </header>
              <div class="panel-body">
              <div class="adv-table table-container">
              <table  class="display table table-bordered table-striped" id="dynamic-table">
              <thead>
              <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Bangla Name</th>
                  <th>Division Name</th>
                  <th>Status</th>
                  <th>Action</th>
              </tr>
              </thead>
              <tbody>
                @if(!empty($districts))
                @foreach($districts as $dist)
              <tr class="gradeX">
                  <td>{{$dist->id}}</td>
                  <td>{{$dist->name}}</td>
                  <td>{{$dist->bn_name}}</td>
                  <td>{{$dist->divi_name}}</td>
                  <td>@if($dist->status == 0)
                    <a href="#"><span class="label label-danger" style="font-size: 11px;">Deactive</span></a>
                    @endif
                    @if($dist->status == 1)
                    <a href="#"><span class="label label-success" style="font-size: 11px;">Active</span></a>
                   @endif</td>
                  <td>
                    <ul class="list-unstyled list-inline">
                    <li><a href="{{ route('district.edit', $dist->id) }}" class="tooltip-success" data-rel="tooltip" title="Edit">
                        <i class="fa fa-pencil-square-o"></i></a></li>
                    <li><a href="#" class="delete remove-btn" href="#" data-toggle="modal" data-target="#destroy-item" value="{{ $dist->id }}">
                <i class="fa fa-trash-o"></i></a></li>
                  </ul> </td>
              </tr>
              @endforeach
              @endif
              </tbody>
              <tfoot>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Bangla Name</th>
                <th>Division</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
              </tfoot>
              </table>
              </div>
              </div>
              </section>
              </div>
              </div>
      </section>
      <!-- Create item modal -->
<div class="modal fade" id="create-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document">
  <div class="modal-content">
     <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Add District</h4>
     </div>
     <div class="modal-body">
       <form method="POST" action="{{route('district.store')}}" accept-charset="UTF-8">
         {{ csrf_field() }}
       <fieldset>
        <div class="form-group">
           <label for="division_id">Division</label>
           <select class="form-control" name="division_id" id="division_id">
             <option value="">Select</option>
             @if(!empty($divisions))
             @foreach($divisions as $division)
             <option value="{{$division->id}}">{{$division->name}}</option>
             @endforeach
             @endif
           </select>
        </div>
        <div class="form-group">
           <label for="name">District Name</label>
           <input type="text" name="name" id="name" class="form-control">
        </div>
        <div class="form-group">
           <label for="bn_name">Bangla</label>
           <input type="text" name="bn_name" id="bn_name" class="form-control">
        </div>
        <div class="form-group">
           <label for="lat">Latitude</label>
           <input type="text" name="lat" id="lat" class="form-control">
        </div>
        <div class="form-group">
           <label for="lon">Longitude</label>
           <input type="text" name="lon" id="lon" class="form-control">
        </div>
        <div class="form-group">
           <label for="website">Website</label>
           <input type="text" name="website" id="website" class="form-control">
        </div>
        <div class="form-group">
           <label for="website">Order By</label>
           <input type="text" name="order_id" id="order_id" class="form-control">
        </div>
       </fieldset>
       <div class="modal-footer">
        <button type="submit" class="btn btn-success" id="store-submit">Save</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
       </div>
      </form>
     </div>
  </div>
 </div>
</div>
</section>
<!-- Destroy item modal -->
					<div class="modal fade" id="destroy-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
									<h4 class="modal-title" id="myModalLabel">Delete</h4>
								</div>
								<div class="modal-body" id="remove-data">
									<div class="alert alert-info bigger-110">
										These items will be permanently deleted and cannot be recovered.
									</div>
									<h3 class="text-center">
										<p class="bigger-110 bolder center grey">
											<i class="ace-icon fa fa-hand-o-right blue bigger-120"></i>
											☣Are you sure?☣
										</p>
									</h3>
								</div>
								<div class="modal-footer">
									<form method="post" id="remove-form">
										<input type="hidden" name="id" id="remove-id">
										<button type="submit" class="btn btn-danger">Confirm</button>
										<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
									</form>
								</div>
							</div>
						</div>
					</div>
<script type="text/javascript">
			$('#destroy-item').on('hidden.bs.modal', function () {
				$('#item-not-found').remove();
				$('#remove-data').show();
			});
			$(".table-container").on("click touchstart", ".remove-btn", function () {
				$("#remove-id").val($(this).attr("value"));
			});
			$("#remove-form").submit(function (e) {
				e.preventDefault();
				var CSRF_TOKEN  = $('meta[name="csrf-token"]').attr('content');
				var post_url	= '{{ url("district") }}';
				var msg         = $('#msg');
				var id			= $("#remove-id").val();
				$.ajax({
					type:'POST',
					dataType:'json',
					data:{_token: CSRF_TOKEN, _method: 'DELETE'},
					url: post_url + "/" + id,
					beforeSend: function() {
						$('#item-not-found').remove();
						$('#destroy-loading-bar').show();
					},
					success: function (data) {
						$success = data.responseJSON;
						$.notify({
							// options
							icon: 'fa fa-check',
							title: '<strong>Success</strong>: <br>',
							message: data['msg']
						},{
							// settings
							type: "success",
							allow_dismiss: true,
							newest_on_top: true,
							showProgressbar: false,
							placement: {
								from: "top",
								align: "right"
							},
							offset: 20,
							spacing: 10,
							z_index: 9999,
							delay: 5000,
							timer: 1000,
							mouse_over: "pause",
							animate: {
								enter: 'animated fadeInDown',
								exit: 'animated fadeOutUp'
							}
						});
						$('#destroy-item').modal('toggle');
						// refresh data
						refreshTable();
					},
					error: function(data) {
						$.notify({
							// options
							icon: 'fa fa-exclamation-triangle',
							title: '<strong>Error</strong>: <br>',
							message: 'An error occurred while getting data.'
						},{
							// settings
							type: "danger",
							allow_dismiss: true,
							newest_on_top: true,
							showProgressbar: false,
							placement: {
								from: "top",
								align: "right"
							},
							offset: 20,
							spacing: 10,
							z_index: 9999,
							delay: 5000,
							timer: 1000,
							mouse_over: "pause",
							animate: {
								enter: 'animated fadeInDown',
								exit: 'animated fadeOutUp'
							}
						});
						$('#remove-data').hide();
						(function(){
							var notFound = $('<div class="modal-body fade-text" id="item-not-found"><h1 class="text-center danger">☠</h1><h2 class="text-center">Item not found</h2></div>');
							notFound.insertAfter('#remove-data');
						})();
					},
					complete:function(data) {
					//	$('#destroy-loading-bar').hide();
					}
				});
			});
</script>
<!--main content end-->
@endsection

resources/views/admin/area/division.blade.php
@extends('admin.layouts.app')
@section('title', 'Area | Division')
@section('content')
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
              <!-- page start-->
              <div class="row">
                <div class="col-sm-8 col-md-offset-2">
              <section class="panel">
              <header class="panel-heading">Division<span class="tools pull-right">
                <a class="btn" data-toggle="modal" href="#" data-toggle="modal" data-target="#create-item">Add</a>
                 <a href="javascript:;" class="fa fa-chevron-down"></a>
                 <a href="javascript:;" class="fa fa-times"></a>
             </span>
             @include('admin.layouts.message')
              </header>
              <div class="panel-body">
              <div class="adv-table table-container table-responsive">
              <table  class="display table table-bordered table-striped" id="dyna">
              <thead>
              <tr>
                <th>ID</th>
                  <th>Name</th>
                  <th>Bangla Name</th>
                  <th>Order</th>
                  <th class="text-center">Status</th>
                  <th>Action</th>
              </tr>
              </thead>
              <tbody>
                @if(!empty($divisions))
                @foreach($divisions as $division)
              <tr class="gradeX">
                  <td>{{$division->id}}</td>
                  <td>{{$division->name}}</td>
                  <td>{{$division->bn_name}}</td>
                  <td>{{$division->order_id}}</td>
                  <td class="text-center"><input type="checkbox" class="status" id="" data-id="{{$division->id}}" @if ($division->status) checked @endif></td>
                  <td>
                    <ul class="list-unstyled list-inline">
                    <li><a href="{{ route('division.edit', $division->id) }}" class="tooltip-success" data-rel="tooltip" title="Edit">
                        <i class="fa fa-pencil-square-o"></i></a></li>
                     <li><a href="#" class="delete remove-btn" href="#" data-toggle="modal" data-target="#destroy-item" value="{{ $division->id }}">
             <i class="fa fa-trash-o"></i></a></li>
                    </ul>
                  </td>
              </tr>
              @endforeach
              @endif
              </tbody>
              <tfoot>
              <tr>
                <th>ID</th>
                  <th>Name</th>
                  <th>Bangla Name</th>
                  <th>Order</th>
                  <th class="text-center">Status</th>
                  <th>Action</th>
              </tr>
              </tfoot>
              </table>
              </div>
              </div>
              </section>
              </div>
              </div>
      </section>
</section>
<script>
       $(document).ready(function(){
           $('.status').iCheck({
               checkboxClass: 'icheckbox_square-yellow',
               radioClass: 'iradio_square-yellow',
               increaseArea: '20%'
           });
           $('.status').on('ifClicked', function(event){
               id = $(this).data('id');
               $.ajax({
                   type: 'POST',
                   url: "{{ URL::route('tagStatus') }}",
                   data: {
                       '_token': $('input[name=_token]').val(),
                       'id': id
                   },
                   success: function(data) {
                       // empty
                   },
               });
           });
           $('.status').on('ifToggled', function(event) {
               $(this).closest('tr').toggleClass('warning');
           });
       });

   </script>
<!-- Create item modal -->
<div class="modal fade" id="create-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
<h4 class="modal-title" id="myModalLabel">Add District</h4>
</div>
<div class="modal-body">
 <form method="POST" action="{{route('division.store')}}" accept-charset="UTF-8">
   {{ csrf_field() }}
 <fieldset>
  <div class="form-group">
     <label for="name">Name</label>
     <input type="text" name="name" id="name" class="form-control">
  </div>
  <div class="form-group">
     <label for="bn_name">Bangla</label>
     <input type="text" name="bn_name" id="bn_name" class="form-control">
  </div>
  <div class="form-group">
     <label for="order_id">Order By</label>
     <input type="text" name="order_id" id="order_id" class="form-control">
  </div>
 </fieldset>
 <div class="modal-footer">
  <button type="submit" class="btn btn-success" id="store-submit">Save</button>
  <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
 </div>
</form>
</div>
</div>
</div>
</div>

<!-- Destroy item modal -->
					<div class="modal fade" id="destroy-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
									<h4 class="modal-title" id="myModalLabel">Delete</h4>
								</div>
								<div class="modal-body" id="remove-data">
									<div class="alert alert-info bigger-110">
										These items will be permanently deleted and cannot be recovered.
									</div>
									<h3 class="text-center">
										<p class="bigger-110 bolder center grey">
											<i class="ace-icon fa fa-hand-o-right blue bigger-120"></i>
											☣Are you sure?☣
										</p>
									</h3>
								</div>
								<div class="modal-footer">
									<form method="post" id="remove-form">
										<input type="hidden" name="id" id="remove-id">
										<button type="submit" class="btn btn-danger">Confirm</button>
										<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
									</form>
								</div>
							</div>
						</div>
					</div>
<script type="text/javascript">
			$('#destroy-item').on('hidden.bs.modal', function () {
				$('#item-not-found').remove();
				$('#remove-data').show();
			});
			$(".table-container").on("click touchstart", ".remove-btn", function () {
				$("#remove-id").val($(this).attr("value"));
			});
			$("#remove-form").submit(function (e) {
				e.preventDefault();
				var CSRF_TOKEN  = $('meta[name="csrf-token"]').attr('content');
				var post_url	= '{{ url("division") }}';
				var msg         = $('#msg');
				var id			= $("#remove-id").val();
				$.ajax({
					type:'POST',
					dataType:'json',
					data:{_token: CSRF_TOKEN, _method: 'DELETE'},
					url: post_url + "/" + id,
					beforeSend: function() {
						$('#item-not-found').remove();
						$('#destroy-loading-bar').show();
					},
					success: function (data) {
						$success = data.responseJSON;
						$.notify({
							// options
							icon: 'fa fa-check',
							title: '<strong>Success</strong>: <br>',
							message: data['msg']
						},{
							// settings
							type: "success",
							allow_dismiss: true,
							newest_on_top: true,
							showProgressbar: false,
							placement: {
								from: "top",
								align: "right"
							},
							offset: 20,
							spacing: 10,
							z_index: 9999,
							delay: 5000,
							timer: 1000,
							mouse_over: "pause",
							animate: {
								enter: 'animated fadeInDown',
								exit: 'animated fadeOutUp'
							}
						});
						$('#destroy-item').modal('toggle');
						// refresh data
						refreshTable();
					},
					error: function(data) {
						$.notify({
							// options
							icon: 'fa fa-exclamation-triangle',
							title: '<strong>Error</strong>: <br>',
							message: 'An error occurred while getting data.'
						},{
							// settings
							type: "danger",
							allow_dismiss: true,
							newest_on_top: true,
							showProgressbar: false,
							placement: {
								from: "top",
								align: "right"
							},
							offset: 20,
							spacing: 10,
							z_index: 9999,
							delay: 5000,
							timer: 1000,
							mouse_over: "pause",
							animate: {
								enter: 'animated fadeInDown',
								exit: 'animated fadeOutUp'
							}
						});
						$('#remove-data').hide();
						(function(){
							var notFound = $('<div class="modal-body fade-text" id="item-not-found"><h1 class="text-center danger">☠</h1><h2 class="text-center">Item not found</h2></div>');
							notFound.insertAfter('#remove-data');
						})();
					},
					complete:function(data) {
					//	$('#destroy-loading-bar').hide();
					}
				});
			});
</script>
<!--main content end-->
@endsection

resources/views/admin/area/division_edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Dashboard | Division Edit')
@section('content')
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
              <!-- page start-->
              <div class="row">
                <div class="col-md-6 col-md-offset-3">
              <section class="panel">
              <header class="panel-heading">
                Division
             <span class="tools pull-right">
               <a class="btn" href="{{url('division')}}"><i class="fa fa-undo" aria-hidden="true"></i> Back</a>
                <a href="javascript:;" class="fa fa-chevron-down"></a>
                <a href="javascript:;" class="fa fa-times"></a>
             </span>
             @include('admin.layouts.message')
              </header>
              <div class="panel-body">
              <div class="adv-table">
                <form method="post" action="/division/{{ $division->id }}" accept-charset="UTF-8">
                  {{ method_field('PATCH') }}
                  <input type="hidden" name="id" class="form-control" id="id" value="{{$division->id}}">
                   {{ csrf_field() }}
             <div class="form-group">
                 <label for="name">Name</label>
                 <input type="text" name="name" class="form-control" id="name" value="{{$division->name}}">
                 @if ($errors->has('name'))
                 <p class="help-block">{{ $errors->first('name') }}</p>
                 @endif
             </div>
             <div class="form-group">
                 <label for="name">Bengali</label>
                 <input type="text" name="bn_name" class="form-control" id="bn_name" value="{{$division->bn_name}}">
                 @if ($errors->has('bn_name'))
                 <p class="help-block">{{ $errors->first('bn_name') }}</p>
                 @endif
             </div>
             <div class="form-group">
                 <label for="order_id">Order</label>
                 <input type="text" name="order_id" class="form-control" id="order_id" value="{{$division->order_id}}">
                 @if ($errors->has('order_id'))
                 <p class="help-block">{{ $errors->first('order_id') }}</p>
                 @endif
             </div>
             <div class="modal-footer">
               <button type="submit" class="btn btn-info">Update</button>
                    <button class="btn btn-danger" type="reset">Cancel</button>
           </div>

         </form>
              </div>
              </div>
              </section>
              </div>
              </div>
    </section>
</section>
@endsection